# Generated by Django 5.1.7 on 2025-03-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
